import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// React Query

// Sonner
import { Toaster } from "sonner";
import I18nProvider from "@/components/I18nProvider";
import QueryProvider from "@/components/QueryProvider";
import ProtectedRoute from "@/middleware/ProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute>
          <I18nProvider>
            <QueryProvider>
              <Toaster position="top-right" richColors />
              {children}
            </QueryProvider>
          </I18nProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}
